### ISSUE TITLE
Persian diacritic marks

### ISSUE THREAD

**Issue by miracle2k** [global-asp/global-asp#40]
This is more of a note, in case this was not done on purpose. b8b0c098cc3448d51eebb5f12f7020379b626482 removed the diacritic marks from the Persian text. The Storybooks Canada  Repo still has them.

In general, the multitude of seemingly overlapping repos is be a bit confusing, though I suppose I largely figured it out.

**Comment by dohliam** [comment]
Hi @miracle2k thanks for your interest in the project!

The short answer to your question is that the versions with diacritics were moved to [this repository](https://github.com/global-asp/gasp-alternates) to avoid having vowelled and unvowelled stories mixed together in the same repo.

Longer answer: The Storybooks Canada repo is automatically-generated from this and other source repos. You might have noticed that diacritics (or full vowelling) there are only provided for Level 1 and Level 2 stories in Persian (as well as Arabic and other languages using Arabic orthography). This is because it is not normal for longer texts to contain vowelling diacritics in these languages. However, since we have the fully vowelled versions of all the stories, and these might be valuable for learners and for other purposes, we decided to store all the vowelled versions together in a single place, and keep the versions in this repo entirely unvowelled to represent the "normal" way that native text is presented in these languages. Downstream projects like Storybooks Canada then pull the appropriate vowelled and unvowelled texts from the respective repos and put them together to create the source for the live website.

Hope that makes sense! If you have any questions about the structure of the repos or anything else where documentation might still be a bit lacking, please feel free to let me know.

**Comment by miracle2k** [comment]
That makes perfect sense, thank you!
