### ISSUE TITLE
Wrong ID?

### ISSUE THREAD

**Issue by espensj** [global-asp/global-asp#5]
The story Goat, Dog and Cow has the ID 0315 according to the master list (http://global-asp.github.io/stories/master.html), but it gives Picture book (0253) when I type hte URL for tranlating it.
http://global-asp.github.io/translator/?0315

**Comment by dohliam** [comment]
Thanks for reporting this. This issue is actually related to a larger problem of replacing wordless and duplicate stories.

There are in fact two versions of _Goat, Dog and Cow_ in the collection. The one you were probably looking for is **Story # 0004**. The one you mentioned, Story #0315, is actually a version of _Goat, Dog and Cow_ that has no words. Because it has no words to translate it -- along with other wordless stories -- is not included in the Translator app. It should also be replaced by a new story in the Master Index.

Work on replacing wordless stories and duplicates is ongoing, and a list of candidates from the new ASP queue has been compiled based on your suggestions. The following wordless stories need to be replaced:
- 0027_rain_drop_1
- 0035_day_with_my_doll_0
- 0152_baby_who_cried_0
- 0189_i_know_colours
- 0216_skipping_2
- 0221_what_do_you_see_next_0
- 0237_i_can_do_this_1
- 0239_skipping_3
- 0315_goat_dog_and_cow_0
- 0324_i_am_a_girl_0
- 0336_i_like_0

In addition, Story #0314_what_do_you_like_1 has only one sentence, but is otherwise wordless, and will be replaced as well.

**Comment by dohliam** [comment]
Story 0315 has now been replaced with _Sakima's Song_.
