### ISSUE TITLE
Image missing

### ISSUE THREAD

**Issue by espensj** [global-asp/global-asp#6]
The story If I were..... (#0134) seems to be missing an image, so the translated text is shifted.

Missing image
![screen shot 2015-11-04 at 9 28 30 pm](https://cloud.githubusercontent.com/assets/12679303/10960748/4cf0c4d0-833b-11e5-81aa-d2d8d022fae1.png)

**Comment by dohliam** [comment]
Thanks for catcing this! It looks like this image is indeed missing, so I've replaced it in the [ASP Imagebank repository](https://github.com/global-asp/asp-imagebank).

This can happen sometimes because the pdf extractor script expects the actual story images to be jpgs. In this case, it looks like this image was stored as a png file, like all the decorations and logos that are also in the ASP pdfs, so it was ignored.

**Comment by dohliam** [comment]
@espensj This is now fixed, see [here](https://global-asp.github.io/translator/?0134)
